### ISSUE TITLE
search user predictors in `create_analysis`

### ISSUE THREAD

**Issue by adelavega** [neuroscout/pyNS#79]
`create_analysis` only searches public predictors, not private user uploaded predictors. Add this ability.

see: https://github.com/neuroscout/neuroscout/issues/812

**Comment by adelavega** [comment]
@jsmentch I just realized that this is already implemented, and it should search your private predictors if it fails to find the predictors you named in the public listing.

Can you use ipdb %debug to let me know which specific predictors are not being found.

Basically when it crashes and gives this error, type the following:

```
>>> "Not all named predictors could be found for the "
                "specified runs."
>>> %debug
>>> predictors
>>> predictor_names
```

and let me know what the content of those two variables are for you.

**Comment by jsmentch** [comment]
I did see that line where it searches through the private predictors but figured it wasn't working.

I just tried using my uploaded predictors in create_analysis() again and now there is no error - I don't think I'm doing anything differently but seems to be working now!

**Comment by jsmentch** [comment]
To update this again, I sometimes get the error and sometimes I do not at this point.

Sometimes it will give an error along with this message not letting me debug:
`ERROR:root:No traceback has been produced, nothing to debug.`

Other times it provides the debug prompt but at random? Maybe a problem on my end. It seems to not work when I am adding both predictors at the same time which are from different collections. Here is what I got from when it provided the dbug prompt :
```
ipdb> predictors
[19945, 19949, 19953, 19959, 20495, 20499, 20503, 20507, 20511, 20515, 37921]
ipdb> predictor_names
['rot_x', 'rot_y', 'rot_z', 'trans_x', 'trans_y', 'trans_z', 'global_signal', 'csf', 'white_matter', 'framewise_displacement', 'speaker_id_merlin', 'face_id_qc_gaius']
```
Anyway, in particular, I am running into this issue with: 'face_id_qc_merlin')
```
[{'dataset_id': 5,
  'description': None,
  'id': 37926,
  'name': 'face_id_qc_merlin',
  'private': True,
  'source': 'Collection: face ids for merlin movie'}]
```

and 'speaker_id_merlin'
```
[{'dataset_id': 5,
  'description': None,
  'id': 37911,
  'name': 'speaker_id_merlin',
  'private': True,
  'source': 'Collection: Identified Speaker ID for Merlin Movie'}]
```

**Comment by adelavega** [comment]
hmm, that's pretty strange. can you give me the specific `create_analysis` command you are running so I can try to replicate it. 

it's possible that some of these collections are not linked to all the runs. the function searches for predictors that match all of the runs (which probably would be all the runs for the task). it's possible that if there are any inconsistencies here, it would not be able to find the predictor.

**Comment by jsmentch** [comment]
Sure, here is the command I last used and the result I got:
```
#create an analysis
%debug
analysis = neuroscout.analyses.create_analysis(
    dataset_name='SherlockMerlin', name='logical and face speech',
    description='try to use logical and',
    predictor_names=['rot_x', 'rot_y', 'rot_z', 'trans_x', 'trans_y', 'trans_z', 'global_signal', 'csf', 'white_matter','framewise_displacement', 'speaker_id_merlin','face_id_qc_merlin'],
    task ='MerlinMovie'
)
```
```
ERROR:root:No traceback has been produced, nothing to debug.
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-4-e83ed11f4745> in <module>
     18     #hrf_variables=['face_speech'],   #ValueError: HRF Variables must be a subset of all variables
     19     #subject=['19'],
---> 20     task ='MerlinMovie'
     21 )

/opt/miniconda-latest/lib/python3.7/site-packages/pyns/models/analysis.py in create_analysis(self, name, dataset_name, predictor_names, task, subject, run, session, hrf_variables, contrasts, dummy_contrasts, transformations, **kwargs)
    221         if len(predictors) != len(predictor_names):
    222             raise ValueError(
--> 223                 "Not all named predictors could be found for the "
    224                 "specified runs.")
    225 

ValueError: Not all named predictors could be found for the specified runs.
```

**Comment by adelavega** [comment]
https://github.com/bids-standard/pybids/pull/649#pullrequestreview-472071282

**Comment by adelavega** [comment]
Allright, I looked into it and it was an issue wtih the API. When more than one name is passed to the route that gets your user predictors, it failed. In this PR #80 I added a change so that it will look over the missing predictors when searching your user's predictor list.

I'll merge that PR soon but you should be able to try it by installing it locally (something like the following should do it)

```
pip install -e git+https://github.com/neuroscout/pyns.git@users_preds#egg=pyns
```

**Comment by adelavega** [comment]
Let me know if it fixes your problem and I'll merge that PR

**Comment by adelavega** [comment]
Awesome
